### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by JosephPai** [flrngel/cpc-tensorflow#5]
Thank you for releasing the source code, but I wonder have you got the same result of its paper?

I've rewrite your code and struggling for the result for a couple of days.

**Comment by flrngel** [comment]
I didn't try ImageNet dataset, because it takes so much time.
I just used Fashion MNIST because it's light and complex enough to see CPC's performance.

And my code work is based on [Representation Learning with Contrastive Predictive Coding
](https://arxiv.org/abs/1807.03748) so I'm not sure it can show the same performance with [Data-Efficient Image Recognition with Contrastive Predictive Coding](https://arxiv.org/pdf/1905.09272.pdf)

(But both papers are written/reviewed by same author, Van den oord)

I guess, I should write readme more kindly..
